server:
  port: 8001
spring:
  application:
    name: customer-service
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db-test?useSSL=false
    username: root
    password: root
  jpa:
    database: MYSQL
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30