server:
  port: 8082
spring:
  application:
    name: sale-service
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db-test?useSSL=false
    username: root
    password: root
  jpa:
    database: MYSQL
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
client:
  customer-service: http://192.168.36.1:8080
  product-service: http://192.168.36.1:8081